language: java
sudo: false
jdk:
- oraclejdk8
env:
  global:
  - DISPLAY=:99.0
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
git:
  submodules: false
before_install:
- sh -e /etc/init.d/xvfb start - sleep 10
- git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
- ". /tmp/BuildUtilities/travis-ci/installMaven.sh"
- echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc
install: true
script:
- mvn -f my.mavenized.herolanguage.releng/pom.xml clean install
- mvn -f example-project/pom.xml clean install
